### ISSUE TITLE
Error: invalid multibyte character in parser at line 4

### ISSUE THREAD

**Issue by paddygoat** [YvesBas/Tadarida-L#3]
tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida-L-master/Paddy_bats$ Rscript write_tabase3HF.R
randomForest 4.6-12
Type rfNews() to see new features/changes/bug fixes.
[1] "2019-10-20 13:11:28 BST"
[1] "2019-10-20 13:11:29 BST"
[1] "2019-10-20 13:11:29 BST"
[1] "2019-10-20 13:11:34 BST"
tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida-L-master/Paddy_bats$ Rscript buildClassif_HF.R
randomForest 4.6-12
Type rfNews() to see new features/changes/bug fixes.
[1] "2019-10-20 13:11:42 BST"
Error: invalid multibyte character in parser at line 4
Execution halted
tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida-L-master/Paddy_bats$ 

Ubuntu 18.

I tried to research this error - is it possibly because I am in UK and not using French acutes?

I deleted all the species in SpeciesList.csv to get rid of non standard characters, except for the 5 that I'm interested in, but no luck. 

Is there anywhere else that characters could be a problem or am I the dog barking up the wrong tree?

Thanks !!!!

The most likely cause is that your scripts are written in an "8 bit ASCII" encoding (Latin-1 or -9, most likely), while R is running in a UTF8 locale. If that is the cause, the fix is to standardize things to use the same locale. You can convert the encoding of your source file using the iconv utility (in a Terminal window).
Or use the 'encoding' argument of source() to tell R what the encoding
is, e.g. encoding="latin1" or "latin-9" (the inconsistency being in
the iconv used on Macs, not in R).

tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida_L_master/Paddy_bats$ Rscript buildClassif_HF.R encoding="latin-9"
randomForest 4.6-12
Type rfNews() to see new features/changes/bug fixes.
[1] "2019-10-20 14:42:06 BST"
Error: invalid multibyte character in parser at line 4
Execution halted
tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida_L_master/Paddy_bats$ Rscript buildClassif_HF.R encoding="latin-1"
randomForest 4.6-12
Type rfNews() to see new features/changes/bug fixes.
[1] "2019-10-20 14:42:23 BST"
Error: invalid multibyte character in parser at line 4
Execution halted
tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida_L_master/Paddy_bats$ Rscript buildClassif_HF.R encoding="UTF-8"
randomForest 4.6-12
Type rfNews() to see new features/changes/bug fixes.
[1] "2019-10-20 14:45:51 BST"
Error: invalid multibyte character in parser at line 4
Execution halted
tegwyn@Fartyarse:/media/tegwyn/BAT_01/Bat_Files/Tadarida_L_master/Paddy_bats$

**Comment by YvesBas** [comment]
Hi Tegwyn,

I've never seen this error before...
Could you send me your result of write_tabase3HF? (something like
"tabase....csv")?



Le dim. 20 oct. 2019 à 14:19, TegwynTwmffat <notifications@github.com> a
écrit :

**Comment by paddygoat** [comment]
Thanks for reply. I've ditched Ubuntu and moved onto Windows 10 machine. There are now no obvious errors, but training takes only 7 seconds so I have raised another issue.

**Comment by YvesBas** [comment]
It's normal, the RSDB on Github is very small, just for testing it. You
need to gather your own reference data to build an efficient classifier

Le lun. 21 oct. 2019 à 16:11, TegwynTwmffat <notifications@github.com> a
écrit :
