### ISSUE TITLE
Lien Erroné sur le wiki 

### ISSUE THREAD

**Issue by samuelortion** [YvesBas/Tadarida-L#5]
Il y a une erreur sur le wiki ([https://github.com/YvesBas/Tadarida-L/wiki](https://github.com/YvesBas/Tadarida-L/wiki)), le lien 'HERE' renvoi vers la création d'une page github, contrairement à la publication attendue. 
Cordialement, 
Samuel Ortion

**Comment by YvesBas** [comment]
merci
